apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: task-package-test
  namespace: wcare-ns
spec:
  inputs:
    resources:
      - name: source-repo
        type: git
  steps:
    - name: build
      image: maven:3.6.3-jdk-11-slim
      workingdir: $(inputs.resources.source-repo.path)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          mvn package
    - name: test
      image: maven:3.6.3-jdk-11-slim
      workingdir: $(inputs.resources.source-repo.path)
      command: ["/bin/bash"]
      args:
        - -c
        - |
          set -e
          mvn test
